name: saisc-containers-dev

services:
  postgresql:
    image: postgres:17-alpine
    container_name: saisc-postgresql-dev
    ports:
      - "58081:5432"
    environment:
      - POSTGRES_USER=saisc
      - POSTGRES_PASSWORD=saisc
      - POSTGRES_DB=saisc
    volumes:
      - saisc_postgres_data_dev:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  saisc_postgres_data_dev:
